init-dev:
	cd env/dev && terraform init

plan-dev:
	cd env/dev && terraform plan

apply-dev:
	cd env/dev && terraform apply -auto-approve

destroy-dev:
	cd env/dev && terraform destroy -auto-approve

init-pro:
	cd env/pro && terraform init

plan-pro:
	cd env/pro && terraform plan

apply-pro:
	cd env/pro && terraform apply -auto-approve

destroy-pro:
	cd env/pro && terraform destroy -auto-approve