variable "exposed_web_port" {}
variable "exposed_prometheus_port" {}
variable "postgres_user" {}
variable "postgres_password" {}
variable "postgres_db" {}
variable "grafana_port" {}
variable "grafana_user" {}
variable "grafana_password" {}
variable "minio_port" {}
variable "minio_user" {}
variable "minio_password" {}