variable "name" {}
variable "environment" {}
variable "postgres_connection" {}
variable "redis_connection" {}
variable "network_id" {}
variable "build_context" {}
variable "dockerfile" {}
variable "minio_user" {}
variable "minio_password" {}